apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls
  namespace: immich
spec:
  secretName: immich-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "images.yadunut.dev"
