apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v2
            env:
              - name: REDIS_HOSTNAME
                value: immich-valkey
              - name: IMMICH_MACHINE_LEARNING_URL
                value: http://immich-machine-learning:3003
              - name: DB_HOSTNAME
                value: immich-postgres-rw
              - name: DB_USERNAME
                value: immich
              - name: DB_DATABASE_NAME
                value: immich
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: password

    immich:
      persistence:
        library:
          existingClaim: immich-library

    valkey:
      enabled: true
      persistence:
        data:
          enabled: true
          type: persistentVolumeClaim
          size: 1Gi
          accessMode: ReadWriteOnce

    server:
      enabled: true
      ingress:
        main:
          enabled: true
          className: traefik
          hosts:
            - host: images.yadunut.dev
              paths:
                - path: /
                  service:
                    identifier: main
          tls:
            - secretName: immich-tls
              hosts:
                - images.yadunut.dev
          annotations:
            traefik.ingress.kubernetes.io/proxy-body-size: "0"

    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
