apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: yadunut-dev
  namespace: external-dns
spec:
  endpoints:
    - dnsName: yadunut.dev
      recordTTL: 300
      recordType: AAAA
      targets:
        - "2400:79e0:403:d070:5a47:caff:fe7f:c65d"
    - dnsName: yadunut.dev
      recordTTL: 300
      recordType: A
      targets:
        # nut-gc2 IP:
        - "103.149.46.7"
        # # nut-gc1 IP:
        # - "167.253.159.47"
    - dnsName: "*.yadunut.dev"
      recordTTL: 300
      recordType: AAAA
      targets:
        - "2400:79e0:403:d070:5a47:caff:fe7f:c65d"
    - dnsName: "*.yadunut.dev"
      recordTTL: 300
      recordType: A
      targets:
        # nut-gc2 IP:
        - "103.149.46.7"
        # nut-gc1 IP:
        # - "167.253.159.47"
