apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llama-tls
  namespace: llama
spec:
  secretName: llama-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - llm.yadunut.dev
