apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-models
  namespace: llama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 30Gi
