apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: books-tls
  namespace: books
spec:
  secretName: books-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "books.yadunut.dev"
