apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-config
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-library
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-ingest
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 1Gi
