apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  instances: 1

  storage:
    size: 10Gi
    storageClass: longhorn-postgres

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
