apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  instances: 3

  storage:
    size: 10Gi
    storageClass: longhorn-local-1r

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
