apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - onepassworditem.yaml
  - llama-onepassworditem.yaml
  - database-onepassworditem.yaml
  - database.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: litellm-config
    namespace: litellm
    files:
      - config.yaml
      - patch-chatgpt.py
