apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-auth
  namespace: litellm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 1Gi
