apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: alloy
      version: 0.*
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      type: deployment

    alloy:
      configMap:
        content: |-
          logging {
            level  = "info"
            format = "logfmt"
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              regex         = "(.+)"
              target_label  = "namespace"
              action        = "replace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              regex         = "(.+)"
              target_label  = "pod"
              action        = "replace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              regex         = "(.+)"
              target_label  = "container"
              action        = "replace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              regex         = "(.+)"
              target_label  = "node"
              action        = "replace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_kind"]
              regex         = "(.+)"
              target_label  = "workload_type"
              action        = "replace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_name"]
              regex         = "(.+)"
              target_label  = "workload"
              action        = "replace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              regex         = "(.+)"
              target_label  = "app"
              action        = "replace"
            }

            rule {
              source_labels = ["app", "__meta_kubernetes_pod_label_app"]
              separator     = ";"
              regex         = ";(.+)"
              replacement   = "$1"
              target_label  = "app"
              action        = "replace"
            }

            rule {
              source_labels = ["app"]
              regex         = "(.+)"
              target_label  = "service_name"
              action        = "replace"
            }

            rule {
              source_labels = ["service_name", "container"]
              separator     = ";"
              regex         = ";(.+)"
              replacement   = "$1"
              target_label  = "service_name"
              action        = "replace"
            }
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki.monitoring.svc.k8s.internal:3100/loki/api/v1/push"
            }
          }
