apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  itemPath: "vaults/cluster/items/grafana-admin"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  itemPath: "vaults/cluster/items/grafana-oidc"

