apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - grafana-onepassworditems.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - flux-podmonitor.yaml
  - loki-helmrelease.yaml
  - alloy-helmrelease.yaml
  - grafana-certificate.yaml
  - grafana-ingressroute.yaml
