apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-local-1r
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
