apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drive-tls
  namespace: drive
spec:
  secretName: drive-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "drive.yadunut.dev"

