apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  namespace: drive
  labels:
    app: copyparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      containers:
        - name: copyparty
          image: copyparty/ac
          args:
            - "-c"
            - "/config/copyparty.conf"
          ports:
            - containerPort: 3923
              protocol: TCP
          env:
            - name: HTTPS_PROXY
              value: "http://http-proxy.kube-system.svc.k8s.internal:8888"
            - name: HTTP_PROXY
              value: "http://http-proxy.kube-system.svc.k8s.internal:8888"
            - name: NO_PROXY
              value: ".k8s.internal,.svc,localhost,127.0.0.1,10.0.0.0/8,fd00::/8"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: drive-config
              mountPath: /cfg/copyparty
      volumes:
        - name: config
          configMap:
            name: copyparty-config
            items:
              - key: copyparty.conf
                path: copyparty.conf
        - name: data
          persistentVolumeClaim:
            claimName: drive-data
        - name: drive-config
          persistentVolumeClaim:
            claimName: drive-config
