apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drive-data
  namespace: drive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drive-config
  namespace: drive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

