apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - drive-pvc.yaml
  - deployment.yaml
  - service.yaml
  - oauth2-proxy-onepassworditem.yaml
  - oauth2-proxy-helmrelease.yaml
  - middleware.yaml
  - ingressroute.yaml

