# HTTP Proxy for IPv6-only pods to reach IPv4-only services
# Uses hostNetwork to access the node's IPv4 connectivity
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
  namespace: kube-system
data:
  squid.conf: |
    http_port [::]:8888

    # Keep connect attempts bounded so failed destinations do not stall clients.
    connect_timeout 10 seconds

    # Restrict proxied destination ports to common HTTP/HTTPS.
    acl SSL_ports port 443
    acl Safe_ports port 80
    acl Safe_ports port 443
    acl CONNECT method CONNECT
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports

    # Internal cluster DNS names must bypass proxy via NO_PROXY on clients.
    # This proxy is intended for internet egress.
    http_access allow all

    # We want egress proxying, not response caching.
    cache deny all

    # Avoid adding intermediary headers to proxied traffic.
    via off
    forwarded_for delete
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http-proxy
  namespace: kube-system
  labels:
    app: http-proxy
spec:
  selector:
    matchLabels:
      app: http-proxy
  template:
    metadata:
      labels:
        app: http-proxy
    spec:
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: squid
          image: ubuntu/squid:6.13-25.04_beta@sha256:3de2e64f0ca6efdac3e98557607dc0f23050037f3885016d5d5bfcf9950501b8
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: squid-config
---
apiVersion: v1
kind: Service
metadata:
  name: http-proxy
  namespace: kube-system
spec:
  selector:
    app: http-proxy
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
