---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password-repo
  namespace: 1password-system
spec:
  interval: 15m0s
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password-system
spec:
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: 1password-repo
      version: 1.17.x
  interval: 1m0s
  values:
    connect:
      serviceType: ClusterIP
      credentialsName: 1password-credentials
      credentialsKey: password
    operator:
      create: true
      autoRestart: true
      token:
        name: 1password-token
        key: password

