apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1h
  chart:
    spec:
      chart: harbor
      version: 1.18.*
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    existingSecretAdminPassword: harbor-admin-password
    existingSecretAdminPasswordKey: password
    existingSecretSecretKey: harbor-secret-key
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.yadunut.dev
        className: traefik
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
    externalURL: https://harbor.yadunut.dev
    persistence:
      enabled: true
    trivy:
      enabled: true
    metrics:
      enabled: true
