apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  itemPath: "vaults/cluster/items/harbor-admin-password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  itemPath: "vaults/cluster/items/harbor-secret-key"
