apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent-protonvpn-canary
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: qbittorrent-protonvpn-canary
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: penguin
  containers:
    - name: gluetun
      image: qmcgaw/gluetun:v3.41.1
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      env:
        - name: TZ
          value: Asia/Singapore
        - name: VPN_SERVICE_PROVIDER
          value: custom
        - name: VPN_TYPE
          value: wireguard
        - name: WIREGUARD_ENDPOINT_IP
          value: "2a02:6ea0:d101:6221::10"
        - name: WIREGUARD_ENDPOINT_PORT
          value: "51820"
        - name: WIREGUARD_PUBLIC_KEY
          value: nwlXvRGPmqXIlMFt5MAO6KoVHmgTk2AZbPMXXkDaxQM=
        - name: WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL
          value: 25s
        - name: VPN_PORT_FORWARDING
          value: "on"
        - name: VPN_PORT_FORWARDING_PROVIDER
          value: protonvpn
        - name: VPN_PORT_FORWARDING_UP_COMMAND
          value: /bin/sh -c 'echo "forwarded port {{PORT}}"'
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: qbittorrent-protonvpn
              key: WIREGUARD_PRIVATE_KEY
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              name: qbittorrent-protonvpn
              key: WIREGUARD_ADDRESSES
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "fd00:10:96::/48"
        - name: DNS_UPSTREAM_IPV6
          value: "on"
        - name: HEALTH_TARGET_ADDRESSES
          value: "ipv6.google.com:443,cloudflare.com:443"
        - name: HEALTH_ICMP_TARGET_IPS
          value: "2606:4700:4700::1111,2001:4860:4860::8888"
        - name: HEALTH_RESTART_VPN
          value: "off"
        - name: HEALTH_SERVER_ADDRESS
          value: ":9999"
      ports:
        - name: health
          containerPort: 9999
      volumeMounts:
        - name: tun
          mountPath: /dev/net/tun
  volumes:
    - name: tun
      hostPath:
        path: /dev/net/tun
        type: CharDevice
