apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  path: ./cluster/apps/forgejo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
