apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - books.yaml
  - forgejo.yaml
  - immich.yaml
  - jellyfin.yaml
  - metube.yaml
  - woodpecker.yaml
  - drive.yaml
  - yadunut-dev.yaml
