apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: llama
  interval: 10m0s
  path: ./cluster/apps/litellm
  prune: true
  wait: true
  timeout: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
