apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-tls
  namespace: headlamp
spec:
  secretName: headlamp-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "headlamp.yadunut.dev"
