---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-1password
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infra/controllers/1password
  dependsOn:
  - name: infra-metallb-config
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-1password-config
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infra/configs/1password
  dependsOn:
  - name: infra-1password
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
