---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-authentik
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./infra/controllers/authentik
  dependsOn:
  - name: infra-1password-config
  - name: infra-traefik
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
