---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  itemPath: "vaults/cluster/items/harbor-admin-password"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 15m0s
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: v1.15.x
  interval: 1m0s
  releaseName: harbor
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: wildcard-cert-yadunut.dev-prod
      ingress:
        hosts:
          core: harbor.yadunut.dev
    externalURL: https://harbor.yadunut.dev
    existingSecretAdminPassword: harbor-admin-password
    existingSecretAdminPasswordKey: password
