apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: woodpecker-tls
  namespace: woodpecker
spec:
  secretName: woodpecker-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "ci.yadunut.dev"
