apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: copyparty-tls
  namespace: jellyfin
spec:
  secretName: copyparty-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "media-upload.yadunut.dev"
