apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bazarr-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-bazarr-oauth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-sonarr-oauth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: jellyseerr-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-jellyseerr-oauth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-radarr-oauth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prowlarr-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-prowlarr-oauth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qbittorrent-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-qbittorrent-oauth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: copyparty-oauth
  namespace: jellyfin
spec:
  itemPath: "vaults/cluster/items/jellyfin-upload-oauth"
