apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local-1r
  resources:
    requests:
      storage: 5Gi
