---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-yadunut.dev-staging
  namespace: cert-manager-certs
spec:
  secretName: wildcard-cert-yadunut.dev-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "yadunut.dev"
    - "*.yadunut.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-yadunut.dev-prod
  namespace: cert-manager-certs
spec:
  secretName: wildcard-cert-yadunut.dev-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "yadunut.dev"
    - "*.yadunut.dev"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-i.yadunut.dev-prod
  namespace: cert-manager-certs
spec:
  secretName: wildcard-cert-i.yadunut.dev-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "i.yadunut.dev"
    - "*.i.yadunut.dev"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
