apiVersion: apps/v1
kind: Deployment
metadata:
  name: yadunut-dev
  namespace: yadunut-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yadunut-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yadunut-dev
    spec:
      imagePullSecrets:
        - name: yadunut-dev-harbor
      containers:
        - name: yadunut-dev
          image: harbor.yadunut.dev/yadunut/gleam_nut-site:main@sha256:fa919707da4337f0e1f7ecea4d66e92b1f955a3d2636284e54e0ec9c2ddabb75 # {"$imagepolicy": "flux-system:yadunut-dev"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
