apiVersion: apps/v1
kind: Deployment
metadata:
  name: yadunut-dev
  namespace: yadunut-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yadunut-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yadunut-dev
    spec:
      imagePullSecrets:
        - name: yadunut-dev-harbor
      containers:
        - name: yadunut-dev
          image: harbor.yadunut.dev/yadunut/gleam_nut-site:main@sha256:0c1bc91e0e358aa3acfa5b9f33ef64a7d1eb65ba61073124e156951fe4701675 # {"$imagepolicy": "flux-system:yadunut-dev"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
