apiVersion: apps/v1
kind: Deployment
metadata:
  name: yadunut-dev
  namespace: yadunut-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yadunut-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yadunut-dev
    spec:
      imagePullSecrets:
        - name: yadunut-dev-harbor
      containers:
        - name: yadunut-dev
          image: harbor.yadunut.dev/yadunut/gleam_nut-site:main@sha256:250e40b875f9a44c54e09d4f5d9420d757702bc80d0374bc774c391b5efa2480 # {"$imagepolicy": "flux-system:yadunut-dev"}
          imagePullPolicy: IfNotPresent
          env:
            - name: IMAGE_HOST
              valueFrom:
                secretKeyRef:
                  name: yadunut-dev
                  key: IMAGE_HOST
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: yadunut-dev
                  key: ACCESS_KEY_ID
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: yadunut-dev
                  key: SECRET_ACCESS_KEY
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: yadunut-dev
                  key: REGION
            - name: BUCKET
              value: assets
            - name: IMAGE_PUBLIC_URL
              value: https://assets.web.garage.yadunut.dev
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
