apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - onepassworditem-harbor.yaml
  - onepassworditem.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image-repository.yaml
  - image-policy.yaml
  - image-update-automation.yaml
