apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: yadunut-dev-harbor
  namespace: yadunut-dev
type: kubernetes.io/dockerconfigjson
spec:
  itemPath: "vaults/cluster/items/flux-harbor"
