apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frp-tls
  namespace: frp
spec:
  secretName: frp-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.proxy.yadunut.dev"
