apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-admin-tls
  namespace: litellm
spec:
  secretName: litellm-admin-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - litellm.yadunut.dev
